# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experience.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65xperience.proto\"o\n\x03SAR\x12\r\n\x05state\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x0c\x12\x0e\n\x06reward\x18\x03 \x01(\x0c\x12\x0c\n\x04mask\x18\x04 \x01(\x0c\x12\x0c\n\x04\x64one\x18\x05 \x01(\x05\x12\x0c\n\x04prob\x18\x06 \x01(\x0c\x12\x0f\n\x07version\x18\x07 \x01(\x05\"\x19\n\x04\x45xps\x12\x11\n\x03sar\x18\x01 \x03(\x0b\x32\x04.SARb\x06proto3')



_SAR = DESCRIPTOR.message_types_by_name['SAR']
_EXPS = DESCRIPTOR.message_types_by_name['Exps']
SAR = _reflection.GeneratedProtocolMessageType('SAR', (_message.Message,), {
  'DESCRIPTOR' : _SAR,
  '__module__' : 'experience_pb2'
  # @@protoc_insertion_point(class_scope:SAR)
  })
_sym_db.RegisterMessage(SAR)

Exps = _reflection.GeneratedProtocolMessageType('Exps', (_message.Message,), {
  'DESCRIPTOR' : _EXPS,
  '__module__' : 'experience_pb2'
  # @@protoc_insertion_point(class_scope:Exps)
  })
_sym_db.RegisterMessage(Exps)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SAR._serialized_start=20
  _SAR._serialized_end=131
  _EXPS._serialized_start=133
  _EXPS._serialized_end=158
# @@protoc_insertion_point(module_scope)
